#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VOICE="${VOICE:-Samantha}"

mkdir -p "$ROOT/public/audio/pivots" "$ROOT/public/audio/targets"

generate() {
  local dir=$1 id=$2 text=$3
  local aiff="/tmp/pg-${id}.aiff"
  say -v "$VOICE" -o "$aiff" "$text"
  afconvert -f m4af -d 'aac ' -b 64000 "$aiff" "$ROOT/public/audio/${dir}/${id}.m4a"
  rm -f "$aiff"
  echo "Generated ${dir}/${id}.m4a — \"${text}\""
}

generate pivots want "I want"
generate pivots need "I need"
generate pivots like "I like"
generate pivots have "I have"
generate pivots see "I see a"
generate pivots where "Where is the"
generate pivots look "Look at the"
generate pivots put "Put on"
generate pivots open "Open the"
generate pivots help "Help me with"
generate pivots eat "Eat the"
generate pivots drink "Drink the"
generate pivots more "More"
generate pivots all-done "All done with"

generate targets dog "dog"
generate targets cat "cat"
generate targets bird "bird"
generate targets fish "fish"
generate targets cow "cow"
generate targets horse "horse"
generate targets duck "duck"
generate targets pig "pig"
generate targets rabbit "rabbit"
generate targets lion "lion"
generate targets tiger "tiger"
generate targets bear "bear"
generate targets elephant "elephant"
generate targets monkey "monkey"
generate targets giraffe "giraffe"
generate targets sheep "sheep"
generate targets chicken "chicken"
generate targets turtle "turtle"
generate targets frog "frog"
generate targets apple "apple"
generate targets banana "banana"
generate targets pear "pear"
generate targets watermelon "watermelon"
generate targets strawberry "strawberry"
generate targets grapes "grapes"
generate targets orange "orange"
generate targets cookie "cookie"
generate targets milk "milk"
generate targets water "water"
generate targets juice "juice"
generate targets bread "bread"
generate targets cheese "cheese"
generate targets pizza "pizza"
generate targets egg "egg"
generate targets carrot "carrot"
generate targets rice "rice"
generate targets noodles "noodles"
generate targets sandwich "sandwich"
generate targets yogurt "yogurt"
generate targets cereal "cereal"
generate targets shoes "shoes"
generate targets hat "hat"
generate targets coat "coat"
generate targets ball "ball"
generate targets book "book"
generate targets cup "cup"
generate targets car "car"
generate targets bed "bed"
generate targets potty "potty"
generate targets pee "pee"
generate targets poop "poop"

echo "Done. Voice: $VOICE"
